# Generated by Django 5.2 on 2025-04-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardTitle', models.CharField(max_length=100)),
                ('cardDescription', models.CharField(max_length=300)),
                ('cardDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionType', models.CharField(max_length=150)),
                ('sessionName', models.CharField(max_length=150)),
                ('sessionDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.department')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.healthcard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.team')),
            ],
        ),
        migrations.AddField(
            model_name='healthcard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.team'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('Engineer', 'Engineer'), ('Team Leader', 'Team Leader'), ('Department Leader', 'Department Leader'), ('Senior Manager', 'Senior Manager')], max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.department')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='teamLeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_teams', to='progress.users'),
        ),
        migrations.AddField(
            model_name='department',
            name='departmentLeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_departments', to='progress.users'),
        ),
        migrations.CreateModel(
            name='VotingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteDate', models.DateField()),
                ('vote', models.CharField(choices=[('Green', 'Green'), ('Amber', 'Amber'), ('Red', 'Red')], max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.healthcard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.users')),
            ],
        ),
    ]
